// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe6cduriiGMOHFxewdfMfCizbQaQpjXR4',
    appId: '1:317555003935:web:43b913e9ffbfd229afbb2a',
    messagingSenderId: '317555003935',
    projectId: 'wildlifeer-29cec',
    authDomain: 'wildlifeer-29cec.firebaseapp.com',
    storageBucket: 'wildlifeer-29cec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzM2YZ6HZWNPVB8H76at8qTFPkAK-UDAU',
    appId: '1:317555003935:ios:c7a76549a8ca0c3cafbb2a',
    messagingSenderId: '317555003935',
    projectId: 'wildlifeer-29cec',
    storageBucket: 'wildlifeer-29cec.appspot.com',
    iosBundleId: 'com.wildlifeer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzM2YZ6HZWNPVB8H76at8qTFPkAK-UDAU',
    appId: '1:317555003935:ios:c7a76549a8ca0c3cafbb2a',
    messagingSenderId: '317555003935',
    projectId: 'wildlifeer-29cec',
    storageBucket: 'wildlifeer-29cec.appspot.com',
    iosBundleId: 'com.wildlifeer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe6cduriiGMOHFxewdfMfCizbQaQpjXR4',
    appId: '1:317555003935:web:f5b1bfb363e63327afbb2a',
    messagingSenderId: '317555003935',
    projectId: 'wildlifeer-29cec',
    authDomain: 'wildlifeer-29cec.firebaseapp.com',
    storageBucket: 'wildlifeer-29cec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg7qduu8ujfo0yfITSaLXtnwWyQyq1Wfw',
    appId: '1:317555003935:android:36e35d6e3d27e984afbb2a',
    messagingSenderId: '317555003935',
    projectId: 'wildlifeer-29cec',
    storageBucket: 'wildlifeer-29cec.firebasestorage.app',
  );

}